package com.example.flightsservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import javax.validation.constraints.NotEmpty;


@DynamoDBTable(tableName="Flight")
public class Flight {

    private String id;
    @NotEmpty
    private String originAndDestination;
    private String origin;
    private String destination;
    @NotEmpty
    private String departure;
    @NotEmpty
    private String arrival;
    private Double ticketPrice;
    @NotEmpty
    private String currency;
    private Integer numSeatsColumns;
    private Integer numSeatsRows;
    private String takenSeats;


    public void addTakenSeats(String newSeats) {
        takenSeats += "," + newSeats;
    }

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String flightId) {
        this.id = flightId;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "FlightGSI1", attributeName = "OriginAndDestination")
    public String getOriginAndDestination() {
        return originAndDestination;
    }

    public void setOriginAndDestination(String originAndDestination) {
        this.originAndDestination = originAndDestination;
    }


    @DynamoDBAttribute(attributeName = "Departure")
    public String getDeparture() {
        return departure;
    }

    public void setDeparture(String departure) {
        this.departure = departure;
    }

    @DynamoDBAttribute(attributeName = "Arrival")
    public String getArrival() {
        return arrival;
    }

    public void setArrival(String arrival) {
        this.arrival = arrival;
    }

    @DynamoDBAttribute(attributeName = "TicketPrice")
    public Double getTicketPrice() {
        return ticketPrice;
    }

    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }

    @DynamoDBAttribute(attributeName = "Currency")
    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    @DynamoDBAttribute(attributeName = "NumSeatsColumns")
    public Integer getNumSeatsColumns() {
        return numSeatsColumns;
    }

    public void setNumSeatsColumns(Integer numSeatsColumns) {
        this.numSeatsColumns = numSeatsColumns;
    }

    @DynamoDBAttribute(attributeName = "NumSeatsRows")
    public Integer getNumSeatsRows() {
        return numSeatsRows;
    }


    public void setNumSeatsRows(Integer numSeatsRows) {
        this.numSeatsRows = numSeatsRows;
    }

    @DynamoDBAttribute(attributeName = "TakenSeats")
    public String getTakenSeats() {
        return takenSeats;
    }

    public void setTakenSeats(String takenSeats) {
        this.takenSeats = takenSeats;
    }

    @DynamoDBIgnore
    public String getOrigin() {
        return origin;
    }


    public void setOrigin(String origin) {
        this.origin = origin;
    }

    @DynamoDBIgnore
    public String getDestination() {
        return destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }
}
